Repository openshift/kubefed-operator, pull requests merged in 2019-07, with the labels that each got.

#30 Enable high availability for the controller-manger
  deploy/resources/deployment.yaml
Labels: approved, lgtm, size/XS

#29 Changes to better house-keep the operator (MULTI-90, MULTI-91)
  README.md
  pkg/controller/kubefed/kubefed_controller.go
Labels: approved, lgtm, size/S

#33 Fix the operator for rc2 deployment.
  cmd/manager/main.go
  deploy/resources/deployment.yaml
  kubefed-operator-ci.Dockerfile
Labels: approved, lgtm, size/XS

#34 Explicitly specify the working directory to /
  kubefed-operator-ci.Dockerfile
Labels: approved, lgtm, size/XS

#35 Roll up master
  cmd/manager/main.go
  kubefed-operator-ci.Dockerfile
Labels: approved, lgtm, size/XS

#36 Update CSV to add description for the CRDs
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#7 Updating README file + Changes in CSV description.
  README.md
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#37 Update CSV to add description for the CRDs (release-0.1.0-rc3)
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#38 Update CSV to add description for the CRDs (release-master branch)
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#39 Removing minikube references from the smoke-test script
  scripts/smoke-test.sh
  scripts/teardown.sh
Labels: approved, lgtm, size/S

#40 Add doctoc and fixed typo in README file.
  README.md
Labels: approved, lgtm, size/S

#41 Add a definition for the olm-e2e test target
  Makefile.ci
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/olm-e2e.sh
  scripts/teardown.sh
Labels: approved, lgtm, size/M

#45 Update default value for the kubefed-operator image location
  README.md
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/S

#50 Add script to sync kubefed CRD manifests
  deploy/crds/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/crds/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/crds/core_v1alpha1_propagatedversion_crd.yaml
  deploy/crds/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  deploy/crds/core_v1beta1_kubefedconfig_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_dnsendpoint_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_domain_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_servicednsrecord_crd.yaml
  deploy/crds/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_propagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_kubefedconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_dnsendpoint_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_domain_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_servicednsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  scripts/sync-manifests.sh
Labels: approved, lgtm, size/L

#19 Operator should watch all namespaces when deployed in a cluster-scoped mode via OLM
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#51 Add manifests for a productized version of the operator
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_propagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_kubefedconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/image-references
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_dnsendpoint_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_domain_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_servicednsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/operator_v1alpha1_kubefed_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  deploy/olm-catalog/kubefed-operator/art.yaml
  hack/catalog.sh
  pkg/controller/common/extensions.go
  pkg/controller/common/transform.go
  pkg/controller/kubefed/kubefed_controller.go
  pkg/controller/kubefedwebhook/kubefedwebhook_controller.go
  pkg/controller/kubefedwebhook/openshift/openshift.go
Labels: approved, lgtm, size/XXL
