Repository openshift/kubefed-operator, pull requests merged in 2019-06, with the labels that each got.

#3 Add OWNERS file to the repo
  OWNERS
Labels: size/S

#2 First round of changes for building and packaging operator.
  build/Dockerfile
  deploy/crds/kubefed-operator-ClusterPropagatedVersion_crd.yaml
  deploy/crds/kubefed-operator-DNSEndpoint_crd.yaml
  deploy/crds/kubefed-operator-Domain_crd.yaml
  deploy/crds/kubefed-operator-FederatedServiceStatus_crd.yaml
  deploy/crds/kubefed-operator-FederatedTypeConfig_crd.yaml
  deploy/crds/kubefed-operator-IngressDNSRecord_crd.yaml
  deploy/crds/kubefed-operator-KubeFedCluster_crd.yaml
  deploy/crds/kubefed-operator-KubeFedConfig_crd.yaml
  deploy/crds/kubefed-operator-PropagatedVersion_crd.yaml
  deploy/crds/kubefed-operator-ReplicaSchedulingPreference_crd.yaml
  deploy/crds/kubefed-operator-ServiceDNSRecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-ClusterPropagatedVersion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-DNSEndpoint_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-Domain_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-FederatedServiceStatus_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-FederatedTypeConfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-IngressDNSRecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-KubeFedCluster_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-KubeFedConfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-PropagatedVersion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-ReplicaSchedulingPreference_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-ServiceDNSRecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/operator_v1alpha1_kubefed_crd.yaml
  deploy/olm-catalog/kubefed-operator/kubefed-operator.package.yaml
  deploy/operator.yaml
  scripts/install-kubefed.sh
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#4 Add an initial ci make file
  Makefile.ci
Labels: approved, lgtm, size/S

#5 Fix the makefile spacing issue
  Makefile.ci
Labels: approved, lgtm, size/XS

#6 Tabs are not spaces
  Makefile.ci
Labels: approved, lgtm, size/XS

#8 Replace the packages from pmorie to openshift
  cmd/manager/main.go
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_kubefed.go
  pkg/controller/kubefed/kubefed_controller.go
Labels: approved, lgtm, size/S

#9 Update the README to run operator correctly
  README.md
Labels: approved, lgtm, size/XS

#10 Add a new Dockerfile for CI
  kubefed-operator-ci.Dockerfile
Labels: approved, lgtm, size/M

#1 Smoke test for the cluster-scoped deployment
  README.md
  deploy/crds/operator_v1alpha1_kubefed_cr.yaml
  hack/catalog.sh
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
  scripts/teardown.sh
  test/e2e/kubefed_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#13 Fix MULTI-95: Change the in-place image field modification in the CSV
  scripts/install-kubefed.sh
Labels: approved, lgtm, size/S

#12 Adding more accurate time for the `retryInterval` parameter
  test/e2e/kubefed_test.go
Labels: approved, lgtm, size/XS

#17 Adding a log message in controller for the version field + update CSV description
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  pkg/controller/kubefed/kubefed_controller.go
Labels: approved, lgtm, size/XS

#18 Add a meaningful code under unit and vet targets
  Makefile.ci
Labels: approved, lgtm, size/S

#21 Update the deployment yaml to point to rc2 upstream release image
  deploy/resources/deployment.yaml
Labels: approved, lgtm, size/XS

#22 Update the kubefed image that the operator deploys in the master branch.
  deploy/resources/deployment.yaml
Labels: approved, lgtm, size/XS

#24 Update the readme file for the release branch
  README.md
Labels: approved, lgtm, size/XS

#25 Minor change to the README.md to trigger a image build.
  README.md
Labels: approved, lgtm, size/XS

#23 Updated the kubefed controller manager to v0.1.0-rc3.
  deploy/crds/kubefed-operator-KubeFedConfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator-KubeFedConfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  hack/catalog.sh
  pkg/controller/kubefed/kubefed_controller.go
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/L

#26 Update the README file.
  README.md
Labels: approved, lgtm, size/XS
