Repository openshift/kubefed-operator, pull requests merged in 2019-08, with the labels that each got.

#56 Update the package yaml file in kubefed-operator
  README.md
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/image-references
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/kubefed-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  hack/catalog.sh
  scripts/install-kubefed.sh
  scripts/olm-e2e.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/L

#57 Fix read me description for rc4
  README.md
Labels: approved, lgtm, size/XS

#58 Fix wrong filename reference on art.yaml
  deploy/olm-catalog/kubefed-operator/art.yaml
Labels: approved, lgtm, size/XS

#42 Do not hardcode GOARCH/GOOS
  kubefed-operator-ci.Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#59 Fix image reference file to not include productized names in tags
  deploy/olm-catalog/kubefed-operator/4.2/image-references
Labels: approved, lgtm, size/XS

#54 Renaming kubefed.k8s.io-->kubefed.io
  README.md
  deploy/crds/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/crds/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/crds/core_v1alpha1_propagatedversion_crd.yaml
  deploy/crds/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  deploy/crds/core_v1beta1_kubefedconfig_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_dnsendpoint_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_domain_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/crds/multiclusterdns_v1alpha1_servicednsrecord_crd.yaml
  deploy/crds/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1alpha1_propagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_kubefedconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_dnsendpoint_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_domain_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/multiclusterdns_v1alpha1_servicednsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_clusterpropagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_federatedservicestatus_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1alpha1_propagatedversion_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_kubefedconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_dnsendpoint_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_domain_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_ingressdnsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/multicluster_v1alpha1_servicednsrecord_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/scheduling_v1alpha1_replicaschedulingpreference_crd.yaml
  deploy/operator.yaml
  deploy/resources/controller/clusterrole.yaml
  deploy/resources/controller/deployment.yaml
  deploy/resources/controller/role.yaml
  deploy/resources/webhook/webhook.yaml
  deploy/resources/webhook/webhook_deployment.yaml
  deploy/resources/webhook/webhook_role.yaml
  deploy/role.yaml
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/L

#60 Use the tagged version of the images for transforms
  deploy/olm-catalog/kubefed-operator/4.2/image-references
Labels: approved, lgtm, size/XS

#61 Fix olm-e2e script to handle rc branches
  scripts/olm-e2e.sh
Labels: approved, lgtm, size/XS

#43 Update CSV to reflect the install process for the KubeFed
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, kind/documentation, lgtm, size/XL

#62 BZ:1741422: Applying upstream PR#880 fix
  deploy/resources/controller/deployment.yaml
  pkg/controller/kubefed/kubefed_controller.go
Labels: approved, lgtm, size/M

#63 Fix BZ-1741468: Default scope for the KubeFed control plane should be Cluster scoped
  deploy/crds/operator_v1alpha1_kubefed_cr.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
  scripts/install-kubefed.sh
Labels: approved, lgtm, size/XS

#64 BZ: 1741422: Remove the scope field from the KubeFedWebHook CR
  deploy/crds/operator_v1alpha1_kubefedwebhook_cr.yaml
  deploy/crds/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/operator_v1alpha1_kubefedwebhook_crd.yaml
  pkg/apis/operator/v1alpha1/kubefedwebhook_types.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/kubefedwebhook/kubefedwebhook_controller.go
Labels: approved, lgtm, size/M

#65 Housekeeping activities
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
  scripts/create-cluster.sh
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/olm-e2e.sh
  scripts/smoke-test.sh
  scripts/teardown.sh
  scripts/util.sh
Labels: approved, lgtm, size/M

#53 Introduce gosec for security checks
  Makefile.ci
Labels: approved, lgtm, size/XS

#66 Update CRDs from rc-5 to rc-6
  deploy/crds/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/core_v1beta1_federatedtypeconfig_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#67 Update image refs to rc6
  README.md
  deploy/resources/controller/deployment.yaml
  deploy/resources/webhook/webhook_deployment.yaml
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/S

#68 Fast forward rc6 to master.
  README.md
  deploy/resources/controller/deployment.yaml
  deploy/resources/webhook/webhook_deployment.yaml
  scripts/download-binaries.sh
  scripts/install-kubefed.sh
  scripts/smoke-test.sh
Labels: approved, lgtm, size/S

#69 Fix the scorecard tests
  pkg/apis/operator/v1alpha1/kubefedwebhook_types.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#70 Updates for CRD and operator yamls
  deploy/crds/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/olm-catalog/kubefed-operator/0.1.0/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/olm-catalog/kubefed-operator/4.2/operator_v1alpha1_kubefedwebhook_crd.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#71 Keep alm-examples for those CRs which gets reconciled by the operator
  deploy/olm-catalog/kubefed-operator/0.1.0/kubefed-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/kubefed-operator/4.2/kubefed-operator.v4.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#72 Update the value of DEFAULT_KUBEFED_SCOPE env if it exists
  pkg/controller/kubefed/kubefed_controller.go
Labels: approved, lgtm, size/S
